### PR TITLE
[WIP] Dockerfile created to use Universal Base Image

### PR DESCRIPTION
**Pull request by pleimer**

### CODE REVIEW

**Comment by paramite** [comment]
I would maybe add a image build with this Dockerfile to a Travis CI run. Otherwise it seems ok to me.

**Comment by pleimer** [comment]
Good call - it should be running now

**Comment by paramite** [comment]
We will need to figure out from where we gonna get golang in UBI. Travis succeeds, but run_tests.sh fails under the hood with following:
No package epel-release available.
No package golang available.
No package qpid-proton-c-devel available.
./run_tests.sh: line 29: go: command not found  

Oh wow, but it seems that the token is working now: 
$ export COVERALLS_TOKEN=[secure]
Seems like we can close issue #27.

**Comment by leifmadsen** [comment]
When done with this make sure you squash your changes into a single commit that documents what is intended to happen here, and fetch/rebase against the master branch so that you don't have conflicts.

**Comment by leifmadsen** [comment]
This is good work, but we're probably going to have to put it away for a while. Here are relevant BZ to track:

* https://bugzilla.redhat.com/show_bug.cgi?id=1693783
* https://bugzilla.redhat.com/show_bug.cgi?id=1719982

**Comment by leifmadsen** [comment]
@pleimer thanks for investigating this! At this point, we need to work with the Messaging team who we can talk to about getting QPID packages built. We're also blocked on the golang requirement available in UBI. We can revisit this once those packages are available. Thanks much! Great work here.

**Comment by paramite** [comment]
I believe there is work in progress on building QPID stuff in Centos messaging SIG ... just FYI.

**Pull request closed without merging**
